/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2023-12-14 10:04:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import checkCheaper.Goods;
import checkCheaper.OrderGoods;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/header_cart.jsp", Long.valueOf(1701600423906L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1701496442334L));
    _jspx_dependants.put("/menu.jsp", Long.valueOf(1702290992034L));
    _jspx_dependants.put("/header_cart_section.jsp", Long.valueOf(1701600487729L));
    _jspx_dependants.put("/order_buy_form.jsp", Long.valueOf(1701615476435L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("checkCheaper.Goods");
    _jspx_imports_classes.add("checkCheaper.OrderGoods");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      checkCheaper.OrderGoods orderGoods = null;
      orderGoods = (checkCheaper.OrderGoods) _jspx_page_context.getAttribute("orderGoods", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (orderGoods == null){
        orderGoods = new checkCheaper.OrderGoods();
        _jspx_page_context.setAttribute("orderGoods", orderGoods, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

ArrayList<Goods> sessionCart = (ArrayList<Goods>)session.getAttribute("cartlist");

System.out.println("장바구니 리스트 세션 확인용");
if(sessionCart!=null){
	for(int i=0; i<sessionCart.size(); i++){
		System.out.print(sessionCart.get(i).getGoodsName()+" ");
	}
	System.out.println("");
}

      out.write('\r');
      out.write('\n');

if(sessionCart!=null){
	for(Goods e : sessionCart){
		orderGoods.addGoods(e);
	}
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>CheckCheaper</title>\r\n");
      out.write("<!-- Bootstrap CDN -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.3.min.js\" integrity=\"sha256-\r\n");
      out.write("pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\" integrity=\"sha384-\r\n");
      out.write("xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("integrity=\"sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct\"\r\n");
      out.write("crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/footer.css\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/dash_section_input.css\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');

String memberType = (String)session.getAttribute("userType");

      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"./login.jsp\">logout</a>\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"dash.jsp?flag=0\">Home</a>\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"order_history.jsp\">Past Order</a>\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"#\">Book Mark</a>\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"cart.jsp\">Cart</a>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("      <ul class=\"navbar-nav\">\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link active\" aria-current=\"page\" href=\"dash.jsp?flag=0\">Home</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"#\">즐겨찾기</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"order_history.jsp\">주문내역</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"cart.jsp\">장바구니</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        ");

        if(memberType.equals("store")){
        
      out.write("\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"request_goods.jsp\">상품요청</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"store_inventory.jsp\">재고관리</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"store_release.jsp\">출고관리</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        ");

        }
        
      out.write("\r\n");
      out.write("        ");

        if(memberType.equals("admin")){
        
      out.write("\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"confirm_request_goods.jsp\">상품요청확인</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        ");

        }
        
      out.write("\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<div class=\"jumbotron\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h1 class=\"display-2\"><strong>Check to your Cart</strong></h1>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"text-center\">\r\n");
      out.write("			");

			String userID = (String)session.getAttribute("userID");
			out.println("<h3>");
			out.println("Hello, "+userID+"! You can check to your buying cart!");
			out.println("</h3>");
			
      out.write("\r\n");
      out.write("			<br><br>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		<table class=\"table\" style=\"margin-bottom : 30px;\">\r\n");
      out.write("			<thead>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th class=\"scope\">#</th>\r\n");
      out.write("					<th class=\"scope\">상품명</th>\r\n");
      out.write("					<th class=\"scope\">판매점</th>\r\n");
      out.write("					<th class=\"scope\">주소</th>\r\n");
      out.write("					<th class=\"scope\">품질</th>\r\n");
      out.write("					<th class=\"scope\">재고수량</th>\r\n");
      out.write("					<th class=\"scope\">가격(단가)</th>\r\n");
      out.write("					<th class=\"scope\">현재선택수량</th>\r\n");
      out.write("					<th class=\"scope\">주문수량 입력</th>\r\n");
      out.write("					<th class=\"scope\">삭제 버튼</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</thead>\r\n");
      out.write("			<tbody>\r\n");
      out.write("			");

			ArrayList<Goods> list = orderGoods.getList();
			boolean sessionCartFlag=false;
			if(sessionCart!=null || list.size()!=0){
				sessionCartFlag=true;
				int num=0;
				for(int i=0; i<list.size(); i++){
			
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					");

					list.get(i).setTableRowNum(num);
					
      out.write("\r\n");
      out.write("					<td>");
      out.print(num++ );
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(list.get(i).getGoodsName());
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(list.get(i).getFranchiseName() );
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(list.get(i).getFranchiseAddress() );
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(list.get(i).getGoodsLevel() );
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(list.get(i).getQuantity() );
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(list.get(i).getPrice() );
      out.write("</td>\r\n");
      out.write("					<td id=\"curCnt");
      out.print(num-1);
      out.write("\">\r\n");
      out.write("					");

						Goods target=null;
						String source=list.get(i).getGoodsName();
						for(Goods t : list){
							if(t.getGoodsName().equals(source)){
								target=t;
							}
						}
					
      out.write("\r\n");
      out.write("						");

						if(target!=null){ 
							out.println(target.getInputQuantity());
						}
						
      out.write("\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("					<form action=\"inputQuantity_process.jsp\">\r\n");
      out.write("						<input type=\"hidden\" name=\"curNum\" value=\"");
      out.print(num-1);
      out.write("\">\r\n");
      out.write("						<input type=\"number\" name=\"inputQuantity\" id=\"inputQuantityId");
      out.print(num-1);
      out.write("\">\r\n");
      out.write("						<button type=\"submit\" class=\"btn btn-success\">수량적용하기</button>\r\n");
      out.write("					</form>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-danger\">\r\n");
      out.write("							<a href=\"cart_delete.jsp?num=");
      out.print(num-1);
      out.write("\">삭제</a>\r\n");
      out.write("						</button>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("			</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("		");

		if(sessionCartFlag){
			out.println("<hr>");
		
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<form action=\"order_process.jsp\">\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("		<label for=\"inputOrderName\">수령인</label>\r\n");
      out.write("		<input type=\"text\" class=\"form-control\" id=\"inputOrderName\" name=\"orderName\" placeholder=\"ex)홍길동\">\r\n");
      out.write("		<label for=\"inputOrderTel\">수령인 전화번호</label>\r\n");
      out.write("		<input type=\"text\" class=\"form-control\" name=\"orderPhone\" id=\"inputOrderTel\" placeholder=\"ex)010-1111-1111\">\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("		<label for=\"inputOrderAddress\">수령지</label>\r\n");
      out.write("		<input type=\"text\" class=\"form-control\" name=\"orderAddress\" id=\"inputOrderAddress\" placeholder=\"ex)서울\">\r\n");
      out.write("		<div class=\"form-check\">\r\n");
      out.write("			<input type=\"radio\" name=\"orderPay\" id=\"payMoney\" value=\"0\">\r\n");
      out.write("			<label class=\"form-check-label\" for=\"payMoney\">현금</label>\r\n");
      out.write("			<input type=\"radio\" name=\"orderPay\" id=\"payCard\" value=\"1\">\r\n");
      out.write("			<label class=\"form-check-label\" for=\"payCard\">카드</label>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"container\" style=\"display:flex; justify-content:center; margin-top:20px;\">\r\n");
      out.write("		<button type=\"submit\" class=\"btn btn-outline-dark btn-lg\">결제하기</button>\r\n");
      out.write("	</div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("		");

		}
		
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<footer class=\"container\">\r\n");
      out.write("	<p>\r\n");
      out.write("		<span>Agency: Hansung University DataBase Team-B</span><br>\r\n");
      out.write("		<span>Admin: 7조</span><br>\r\n");
      out.write("		<span>&copy;Copyright 2023. CheckCheaper. All Rights Reserved.</span>\r\n");
      out.write("	</p>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');

	String userid=(String)session.getAttribute("userID");
	String usertype=(String)session.getAttribute("userType");
	System.out.println(userid+" "+usertype);
	
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
